backend/models/Order.php
<?php

namespace backend\models;

use Yii;
use frontend\models\TourList;
use common\models\User;


/**
 * This is the model class for table "order".
 *
 * @property integer $order_id
 * @property integer $user_id
 * @property integer $tour_list_id
 * @property integer $count
 * @property integer $status
 */
class Order extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'tour_list_id', 'count', 'status'], 'required'],
            [['user_id', 'tour_list_id', 'count', 'status'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'order_id' => 'Order ID',
            'user_id' => 'User ID',
            'tour_list_id' => 'Tour List ID',
            'count' => 'Count',
            'status' => 'Status',
        ];
    }

    public function getTours()
    {
        return $this->hasMany(TourList::className(), ['tour_list_id' => 'tour_list_id']);
    }
    public function getUser()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id']);
    }
}

frontend/models/Order.php
<?php

namespace frontend\models;

use frontend\models\TourList;
use Yii;
//use frontend\models\TourList;

/**
 * This is the model class for table "order".
 *
 * @property integer $order_id
 * @property integer $user_id
 * @property integer $tour_list_id
 * @property integer $count
 * @property integer $status
 */
class Order extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'tour_list_id', 'count', 'status'], 'required'],
            [['user_id', 'tour_list_id', 'count', 'status'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'order_id' => 'Order ID',
            'user_id' => 'User ID',
            'tour_list_id' => 'Тур',
            'count' => 'Кількість путівок',
            'status' => 'Status',
        ];
    }
    public function getTours()
    {
        return $this->hasMany(TourList::className(), ['tour_list_id' => 'tour_list_id']);
    }
}

backend/controllers/OrderController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Order;
use backend\models\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $usernames = ['admin'];

        if ($action->id=='error') {
            $this->layout ='outsource';
            return true;
        }

        if (parent::beforeAction($action)) {
// if () {
// $this->layout = 'outsource';
// throw new ForbiddenHttpException('Доступ ограничен');
// }
//
            if (!Yii::$app->user->isGuest && !in_array(\Yii::$app->user->identity->username, $usernames)) {
                $this->layout = 'outsource';

            }

        } else {
            return false;
        }

        return true;
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->order_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->order_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    public function actionPublic($id)
    {
        $model = $this->findModel($id);

        $model->status = 2;
        $model->save();

        return  $this->redirect('/admin/order/index');

    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/OrderController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Order;
use frontend\models\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionMyOrder()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->searchMyOrder(Yii::$app->request->queryParams,Yii::$app->user->identity->id);

        return $this->render('my_order', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('/order/my-order');
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->order_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use frontend\models\TourList;

/* @var $this yii\web\View */
/* @var $model backend\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">

    <?php $form = ActiveForm::begin([
        'method' => 'post',
        'action' => Url::toRoute('/order/create'),
        'options' => ['enctype' => 'multipart/form-data',
            'id' => 'form1']

    ]); ?>

    <?= $form->field($model, 'user_id')->hiddenInput(['value'=>Yii::$app->user->identity->id ])->label(false) ?>

<div class="row">
    <div class="col-md-4">
      <?= $form->field($model, 'tour_list_id')->dropDownList(
                                                        ArrayHelper::map(TourList::find()->all(),
                                                            'tour_list_id', 'name'),
                                                        ['prompt' => 'Обрати тур'],
                                                        ['class'=>'select_departament']);
        //                                            ?>

    </div>
    <div class="col-md-4">
        <?= $form->field($model, 'count')->textInput() ?>

    </div>
    <div class="col-md-4">
        <?= $form->field($model, 'status')->hiddenInput(['value'=>1])->label(false) ?>



        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Замовити' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>


    </div>
</div>


    <?php ActiveForm::end(); ?>

</div>

frontend/views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'order_id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'tour_list_id') ?>

    <?= $form->field($model, 'count') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/order/_view.php
<?php
use yii\helpers\Html;

?>
<!-- EVENT TICKET - START -->


<div class="col-xs-12">

    <div class="event-ticket ">
        <div class="row">
            <div class="col-sm-12">
                <div class="event-ticket-massage">
                    <div class="massage-info">
                        <span><i class="fa fa-calendar"></i>Тривалість -  <?=$model->tours[0]->date_entrance.' - '.$model->tours[0]->date_departure ;?></span>
                        <span><i class="fa fa-user"></i>Кількість путівок - <?=$model->count;?></span>
                        <span><i class="fa fa-money"></i>Ціна - <?= $model->tours[0]->price;?></span>
                        <span><i class="fa fa-money"></i>Загальна вартість - <?=$model->count * $model->tours[0]->price;?></span>

                    </div>
                    <div class="massage-text">
                        <h3><?=$model->tours[0]->name;?></h3>
                        <?=$model->tours[0]->description;?>
                    </div>
                    <div class="massage-info">
                        <div id="qwerty<?=$model->order_id?>" style="display: none"><?= $model->status ?></div>
                        <?php

                        $this->registerJs('
                            var a = parseInt($("#qwerty'.$model->order_id.'").html());

                            if (a == 1){
                            $("#buttonAction'.$model->order_id.'").html("<a class=\'btn btn-primary\' href=\'/admin/order/public?id='.$model->order_id.'\' style=\'margin-top:20px\' data-confirm=\'Бажаєте оформити замовлення?\' data-method=\'post\'>Виконати</a><a class=\'btn btn-success\' href=\'/admin/order/delete?id='.$model->order_id.'\' style=\'margin-top:20px\' data-confirm=\'Ви дійсно бажаєте видалити замовлення?\' data-method=\'post\'>Видалити</a>");

                            }
                            else {
                            $("#buttonAction'.$model->order_id.'").html("<div class=\'panel panel-info\' style=\'max-width: 190px\'><div class=\'panel-heading\' >Замовлення виконано!</div></div>");
                            }
                        ');
                        ?>

                        <div id="buttonAction<?=$model->order_id?>"></div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- EVENT TICKET - END -->

frontend/views/order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Order */

$this->title = 'Create Order';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Order', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'order_id',
            'user_id',
            'tour_list_id',
            'count',
            'status',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
</div>

frontend/views/order/my_order.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Мої замовленні тури';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="order-index">

        <h1><?= Html::encode($this->title) ?></h1>


        <?php
//        print_r($dataProvider);die();
        ?>
        <?  Pjax::begin();?>
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemOptions' => ['class' => 'item'],
            'itemView' => function ($model, $key, $index) {

                return  $this->render('_view', ['model' => $model, 'index'=>$index]);

            },
            'pager' => [
                'firstPageLabel' => '<i class="fa fa-angle-double-left"></i>',
                'lastPageLabel' => '<i class="fa fa-angle-double-right"></i>',
                'prevPageLabel' => '<i class="fa  fa-angle-left"></i>',
                'nextPageLabel' => '<i class="fa  fa-angle-right"></i>',
                'maxButtonCount' => 3,
                'options' => [
                    'tag' => 'ul',
                    'class' => 'pagination',
                ],
            ],
        ]) ?>

        <?  Pjax::end();?>

    </div>
</div>

frontend/views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Order */

$this->title = 'Update Order: ' . $model->order_id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->order_id, 'url' => ['view', 'id' => $model->order_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="container">
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div></div>

frontend/views/order/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Order */

$this->title = $model->order_id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
<div class="order-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->order_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->order_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'order_id',
            'user_id',
            'tour_list_id',
            'count',
            'status',
        ],
    ]) ?>

</div>
</div>